### ISSUE TITLE
NPE when browsing to ACID2 test

### ISSUE THREAD

**Issue by hrj** [radkovo/CSSBox#21]
### URL
http://www.webstandards.org/files/acid2/test.html

### Stack trace

```
java.lang.NullPointerException
	at org.fit.cssbox.layout.HTMLBoxFactory.createSubtreeObject(HTMLBoxFactory.java:173)
	at org.fit.cssbox.layout.HTMLBoxFactory.createBox(HTMLBoxFactory.java:99)
	at org.fit.cssbox.layout.BoxFactory.createBox(BoxFactory.java:734)
	at org.fit.cssbox.layout.BoxFactory.createElementBox(BoxFactory.java:447)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:263)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:309)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createBoxTree(BoxFactory.java:213)
	at org.fit.cssbox.layout.BoxFactory.createSubtree(BoxFactory.java:304)
	at org.fit.cssbox.layout.BoxFactory.createViewportTree(BoxFactory.java:169)
	at org.fit.cssbox.layout.BrowserCanvas.createLayout(BrowserCanvas.java:169)
	at org.fit.cssbox.demo.BoxBrowser.displayURL(BoxBrowser.java:169)
	at org.fit.cssbox.demo.BoxBrowser$4.actionPerformed(BoxBrowser.java:700)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by radkovo** [comment]
Thanks for reporting, fixed. CSSBox does not pass the ACID2 test anyway...

**Comment by hrj** [comment]
I was impressed that CSSBox has implemented margin-collapsing correctly, as well as relative and absolute positioning. Hence tried the ACID2 test.

In gngr I am trying to implement margin-collapsing now.. but the layout code is very convoluted; not as clean as CSSBox.

Have you done any sort of automated testing of CSSBox? For example, with the W3C CSS 2.1 tests?

**Comment by radkovo** [comment]
There were some attempts to to implement the automated tests but I didn't have time to get it work. It's in my to do list but I found it quite complicated to automatically evaluate the rendering results. You do have some automated testing in gngr?

**Comment by hrj** [comment]
Yeah we are using the CSS21 reference tests available from here: https://test.csswg.org/suites/css21_dev/

Each test has a reference html (which is simpler), and the their screenshots can be compared, and thus they can be automated.

Yeah, we just finished automating it in gngr.
