### ISSUE TITLE
NullPointerException for some urls

### ISSUE THREAD

**Issue by mplushnikov** [radkovo/CSSBox#24]
Hello, 
I'm getting NullPointerException during processing of some urls. Unfortunately I don't have any free example of such urls.

```
java.lang.NullPointerException: null
	at cz.vutbr.web.csskit.antlr.CSSInputStream.urlStream(CSSInputStream.java:86) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSInputStream.setEncoding(CSSInputStream.java:253) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.DefaultCSSLexer_CSSLexer.mCHARSET(DefaultCSSLexer_CSSLexer.java:340) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.DefaultCSSLexer_CSSLexer.mTokens(DefaultCSSLexer_CSSLexer.java:3896) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSTokenRecovery.nextToken(CSSTokenRecovery.java:127) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.DefaultCSSLexer.nextToken(DefaultCSSLexer.java:130) ~[jstyleparser-1.21.jar:na]
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143) ~[antlr-runtime-3.5.2.jar:3.5.2]
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137) ~[antlr-runtime-3.5.2.jar:3.5.2]
	at org.antlr.runtime.CommonTokenStream.setup(CommonTokenStream.java:137) ~[antlr-runtime-3.5.2.jar:3.5.2]
	at org.antlr.runtime.CommonTokenStream.LT(CommonTokenStream.java:94) ~[antlr-runtime-3.5.2.jar:3.5.2]
	at cz.vutbr.web.csskit.antlr.DefaultCSSParser_CSSParser.stylesheet(DefaultCSSParser_CSSParser.java:486) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.DefaultCSSParser.stylesheet(DefaultCSSParser.java:253) ~[jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.getAST(CSSParserFactory.java:99) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.feedParser(CSSParserFactory.java:382) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.createTreeParser(CSSParserFactory.java:349) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.parseAndImport(CSSParserFactory.java:306) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.append(CSSParserFactory.java:264) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.append(CSSParserFactory.java:295) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.css.CSSFactory$CSSAssignTraversal.processNode(CSSFactory.java:775) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.css.CSSFactory$CSSAssignTraversal.processNode(CSSFactory.java:744) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.domassign.Traversal.listTraversal(Traversal.java:43) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.css.CSSFactory.getUsedStyles(CSSFactory.java:532) [jstyleparser-1.21.jar:na]
	at cz.vutbr.web.css.CSSFactory.getUsedStyles(CSSFactory.java:552) [jstyleparser-1.21.jar:na]
	at org.fit.cssbox.css.DOMAnalyzer.getStyleSheets(DOMAnalyzer.java:382) [cssbox-4.10.jar:na]
	at org.fit.cssbox.css.DOMAnalyzer.getStyleSheets(DOMAnalyzer.java:394) [cssbox-4.10.jar:na]
```

**Comment by radkovo** [comment]
This was probably caused by a bug in `@charset` processing. It's hopefully fixed but no test case has been provided. Reopen when the problem persists.
