### ISSUE TITLE
InlineBox mistook as BlockBox

### ISSUE THREAD

**Issue by changbaishan** [radkovo/CSSBox#47]
here is a stack dump:

Exception in thread "main" java.lang.ClassCastException: org.fit.cssbox.layout.InlineBox cannot be cast to org.fit.cssbox.layout.BlockBox
	at org.fit.cssbox.layout.BlockBox.computeEfficientMargins(BlockBox.java:749)
	at org.fit.cssbox.layout.ElementBox.initSubtree(ElementBox.java:295)
	at org.fit.cssbox.layout.Viewport.initSubtree(Viewport.java:145)
	at org.fit.cssbox.layout.BrowserCanvas.createLayout(BrowserCanvas.java:172)
	at org.fit.cssbox.layout.BrowserCanvas.createLayout(BrowserCanvas.java:142)

**Comment by tr-mm** [comment]
Can confirm. Version 4.17 can no longer render any of our boxes.

 org.fit.cssbox.layout.InlineBox cannot be cast to org.fit.cssbox.layout.BlockBox: java.lang.ClassCastException: org.fit.cssbox.layout.InlineBox cannot be cast to org.fit.cssbox.layout.BlockBox
        at org.fit.cssbox.layout.BlockBox.computeEfficientMargins(BlockBox.java:756) [cssbox-4.17.jar:]
        at org.fit.cssbox.layout.ElementBox.initSubtree(ElementBox.java:295) [cssbox-4.17.jar:]
        at org.fit.cssbox.layout.Viewport.initSubtree(Viewport.java:145) [cssbox-4.17.jar:]

**Comment by raudus** [comment]
https://www.facebook.com/RaudusExperts/videos/2530384250410587/?t=0

Em seg., 18 de nov. de 2019 às 09:08, tr-mm <notifications@github.com>
escreveu:
