### ISSUE TITLE
demo doesnt work.

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [radkovo/CSSBox#75]
>java -cp %newcp% SimpleBrowser https://github.com/radkovo/CSSBox/blob/e49013460a58bbb14be72174aa364d8c39be8166/src/main/java/org/fit/cssbox/io/DefaultDOMSource.java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error: Cannot invoke "java.awt.Graphics2D.create()" because "g" is null
java.lang.NullPointerException: Cannot invoke "java.awt.Graphics2D.create()" because "g" is null
        at org.fit.cssbox.awt.GraphicsVisualContext.updateMetrics(GraphicsVisualContext.java:159)
        at org.fit.cssbox.awt.GraphicsVisualContext.<init>(GraphicsVisualContext.java:86)
        at org.fit.cssbox.awt.GraphicsEngine.createVisualContext(GraphicsEngine.java:180)
        at org.fit.cssbox.layout.Engine.createLayout(Engine.java:212)
        at org.fit.cssbox.layout.Engine.createLayout(Engine.java:185)
        at org.fit.cssbox.layout.Engine.createLayout(Engine.java:171)
        at org.fit.cssbox.layout.Engine.<init>(Engine.java:82)
        at org.fit.cssbox.awt.GraphicsEngine.<init>(GraphicsEngine.java:77)
        at org.fit.cssbox.awt.BrowserCanvas.<init>(BrowserCanvas.java:82)
        at SimpleBrowser.initComponents(SimpleBrowser.java:84)
        at SimpleBrowser.<init>(SimpleBrowser.java:72)
        at SimpleBrowser.main(SimpleBrowser.java:148)

**Comment by DJFLuFFy-vs-joe** [comment]
i am getting the Error: Cannot invoke "java.awt.Graphics2D.create()" because "g" is null error as well.

**Comment by mikedawson** [comment]
I found the same. However, the BoxBrowser did work. I was able to get it working by following the code from BoxBrowser instead of 'SimpleBrowser'.
